// Code generated by "stringer -type=BatchType"; DO NOT EDIT.

package cql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoggedBatch-0]
	_ = x[UnloggedBatch-1]
	_ = x[CounterBatch-2]
}

const _BatchType_name = "LoggedBatchUnloggedBatchCounterBatch"

var _BatchType_index = [...]uint8{0, 11, 24, 36}

func (i BatchType) String() string {
	if i >= BatchType(len(_BatchType_index)-1) {
		return "BatchType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BatchType_name[_BatchType_index[i]:_BatchType_index[i+1]]
}
