name: ci


on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    uses: upfluence/private-actions/.github/workflows/app-go-test.yml@master
    secrets: inherit
    with:
      go-version-matrix: "['1.16.x']"
    with-cassandra: true
